name: 0xW-Deploy

on:
  push:
    tags:
      - v*



jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Resolve version
        run: |
          echo version=$(git tag | sort -V | tail -1) >> $GITHUB_ENV

      - name: Zipping
        run: |
          zip -r ./0xW-${{ env.version }}.zip ./js ./player ./fxmanifest.lua ./nui-state.lua ./README.md

      - name: Send to Discord Channel
        uses: sinshutu/upload-to-discord@c04454f4fbfd38079cbcd6f68492bd5d427556ce
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ./0xW-${{ env.version }}.zip

